### ISSUE TITLE
Incorrect mapping of add command torch->tensorflow

### ISSUE THREAD

**Issue by Praful932** [OpenMined/threepio#144]
## Description
The example usage as given in the [usage](https://github.com/OpenMined/Threepio/blob/dev/pythreepio/README.md#usage) docs and the [tests](https://github.com/OpenMined/Threepio/blob/master/pythreepio/tests/fixtures/torch.py) file does not run as expected for the `add` command, rather gives an error. Example below 👇

## How to Reproduce
Run this code
```python
import tensorflow as tf
import torch as th
from pythreepio.threepio import Threepio, Command

# Create a threepio translating from pytorch -> tensorflow python
threepio = Threepio("torch", "tf", tf)

# Create your command to translate
args = [
    tf.constant([[1, 0], [0, 1]]),
    tf.constant([[0, 1], [1, 0]])
]
kwargs = {}
cmd = Command("add", args, kwargs)

# Translate the command
translated_cmd = threepio.translate(cmd, lookup_command=True)

# Produces error
translated_cmd[0].execute_routine()
```
`TypeError: add() takes 1 positional argument but 2 were given`

On inspecting 
```python
translated_cmd[0].attrs
```
Output - `['tf', 'keras', 'layers', 'add']`

## Expected Behavior
The expected behaviour should be that, both the args should be added
and according to me `translated_cmd[0].attrs` should contain `['tf', 'math', 'add']`.
## Screenshots
![image](https://user-images.githubusercontent.com/45713796/104084996-28408b00-5272-11eb-823b-9a4bb9aa014b.png)

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.8.6
 - Package Manager Version: pip 20.2.4
 - Browser (if applicable): Google Chrome
 - Browser Version (if applicable): 87.0.4280.88

## Additional Context
I am willing to contribute to this issue.

**Comment by Nolski** [comment]
Good catch! This may be related to issue #16 which hopes to add additional accuracy. We also should be able to resolve this by manually mapping the add command in [translations.py](https://github.com/OpenMined/Threepio/blob/dev/docs-crawler/docs/translations.py#L21)

@Praful932 I'll assign this to you as you mentioned you are interested in contributing to this issue but let me know if you no longer have time and I'll remove it :)

**Comment by Praful932** [comment]
Hi @Nolski This issue seems to be fixed in the `dev` branch 😄. Only persists on the `master` branch and `pypi`. Should be fixed with a new release.
This issue can be closed ✔

![image](https://user-images.githubusercontent.com/45713796/105965649-b2c61e80-60a9-11eb-9738-06bd8552962d.png)
