### ISSUE TITLE
Write inline documentation for pythreepio/pythreepio/threepio.py

### ISSUE THREAD

**Issue by tcp** [OpenMined/threepio#69]
## Where?
[pythreepio/pythreepio/threepio.py](https://github.com/OpenMined/threepio/blob/master/pythreepio/pythreepio/threepio.py)

## Who?

Any developer who wants to work on Threepio should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by Praful932** [comment]
@tcp @cereallarceny Seems like a good first issue. Can I work on this?

**Comment by cereallarceny** [comment]
Sure, go for it!
