### ISSUE TITLE
Write inline documentation for pythreepio/pythreepio/utils.py

### ISSUE THREAD

**Issue by tcp** [OpenMined/threepio#71]
## Where?
[pythreepio/pythreepio/utils.py](https://github.com/OpenMined/threepio/blob/master/pythreepio/pythreepio/utils.py)

## Who?

Any developer who wants to work on Threepio should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by darigovresearch** [comment]
Pull request #140 would resolve this issue

**Comment by darigovresearch** [comment]
@tcp & @cereallarceny can this issue can be closed now as Pull request #140 was merged?
